syntax = "proto3";

package demo;

message Recording {
  message Frame {
    float time = 1;
    message Position {
      string path = 1;

      float x = 2;
      float y = 3;
      float z = 4;
    }
    message Rotation {
      string path = 1;

      float rx = 2;
      float ry = 3;
      float rz = 4;
    }
    message Scale {
      string path = 1;

      float sx = 2;
      float sy = 3;
      float sz = 4;
    }
    message Visibility {
      string path = 1;

      bool visible = 2;
    }
    repeated Position positions = 2;
    repeated Rotation rotations = 3;
    repeated Scale scales = 4;
    repeated Visibility visibilities = 5;
  }
  repeated Frame frames = 1;
}
