// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_main_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_main_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_main_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_main_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_main_2eproto;
namespace demo {
class Recording;
struct RecordingDefaultTypeInternal;
extern RecordingDefaultTypeInternal _Recording_default_instance_;
class Recording_Frame;
struct Recording_FrameDefaultTypeInternal;
extern Recording_FrameDefaultTypeInternal _Recording_Frame_default_instance_;
class Recording_Frame_Node3D;
struct Recording_Frame_Node3DDefaultTypeInternal;
extern Recording_Frame_Node3DDefaultTypeInternal _Recording_Frame_Node3D_default_instance_;
}  // namespace demo
PROTOBUF_NAMESPACE_OPEN
template<> ::demo::Recording* Arena::CreateMaybeMessage<::demo::Recording>(Arena*);
template<> ::demo::Recording_Frame* Arena::CreateMaybeMessage<::demo::Recording_Frame>(Arena*);
template<> ::demo::Recording_Frame_Node3D* Arena::CreateMaybeMessage<::demo::Recording_Frame_Node3D>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace demo {

// ===================================================================

class Recording_Frame_Node3D final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:demo.Recording.Frame.Node3D) */ {
 public:
  inline Recording_Frame_Node3D() : Recording_Frame_Node3D(nullptr) {}
  ~Recording_Frame_Node3D() override;
  explicit PROTOBUF_CONSTEXPR Recording_Frame_Node3D(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Recording_Frame_Node3D(const Recording_Frame_Node3D& from);
  Recording_Frame_Node3D(Recording_Frame_Node3D&& from) noexcept
    : Recording_Frame_Node3D() {
    *this = ::std::move(from);
  }

  inline Recording_Frame_Node3D& operator=(const Recording_Frame_Node3D& from) {
    CopyFrom(from);
    return *this;
  }
  inline Recording_Frame_Node3D& operator=(Recording_Frame_Node3D&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Recording_Frame_Node3D& default_instance() {
    return *internal_default_instance();
  }
  static inline const Recording_Frame_Node3D* internal_default_instance() {
    return reinterpret_cast<const Recording_Frame_Node3D*>(
               &_Recording_Frame_Node3D_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Recording_Frame_Node3D& a, Recording_Frame_Node3D& b) {
    a.Swap(&b);
  }
  inline void Swap(Recording_Frame_Node3D* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Recording_Frame_Node3D* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Recording_Frame_Node3D* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Recording_Frame_Node3D>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Recording_Frame_Node3D& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Recording_Frame_Node3D& from) {
    Recording_Frame_Node3D::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Recording_Frame_Node3D* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "demo.Recording.Frame.Node3D";
  }
  protected:
  explicit Recording_Frame_Node3D(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPathFieldNumber = 11,
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
    kRxFieldNumber = 4,
    kRyFieldNumber = 5,
    kRzFieldNumber = 6,
    kSxFieldNumber = 7,
    kSyFieldNumber = 8,
    kSzFieldNumber = 9,
    kVisibleFieldNumber = 10,
  };
  // string path = 11;
  void clear_path();
  const std::string& path() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_path(ArgT0&& arg0, ArgT... args);
  std::string* mutable_path();
  PROTOBUF_NODISCARD std::string* release_path();
  void set_allocated_path(std::string* path);
  private:
  const std::string& _internal_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_path(const std::string& value);
  std::string* _internal_mutable_path();
  public:

  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 3;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // float rx = 4;
  void clear_rx();
  float rx() const;
  void set_rx(float value);
  private:
  float _internal_rx() const;
  void _internal_set_rx(float value);
  public:

  // float ry = 5;
  void clear_ry();
  float ry() const;
  void set_ry(float value);
  private:
  float _internal_ry() const;
  void _internal_set_ry(float value);
  public:

  // float rz = 6;
  void clear_rz();
  float rz() const;
  void set_rz(float value);
  private:
  float _internal_rz() const;
  void _internal_set_rz(float value);
  public:

  // float sx = 7;
  void clear_sx();
  float sx() const;
  void set_sx(float value);
  private:
  float _internal_sx() const;
  void _internal_set_sx(float value);
  public:

  // float sy = 8;
  void clear_sy();
  float sy() const;
  void set_sy(float value);
  private:
  float _internal_sy() const;
  void _internal_set_sy(float value);
  public:

  // float sz = 9;
  void clear_sz();
  float sz() const;
  void set_sz(float value);
  private:
  float _internal_sz() const;
  void _internal_set_sz(float value);
  public:

  // bool visible = 10;
  void clear_visible();
  bool visible() const;
  void set_visible(bool value);
  private:
  bool _internal_visible() const;
  void _internal_set_visible(bool value);
  public:

  // @@protoc_insertion_point(class_scope:demo.Recording.Frame.Node3D)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr path_;
    float x_;
    float y_;
    float z_;
    float rx_;
    float ry_;
    float rz_;
    float sx_;
    float sy_;
    float sz_;
    bool visible_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_main_2eproto;
};
// -------------------------------------------------------------------

class Recording_Frame final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:demo.Recording.Frame) */ {
 public:
  inline Recording_Frame() : Recording_Frame(nullptr) {}
  ~Recording_Frame() override;
  explicit PROTOBUF_CONSTEXPR Recording_Frame(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Recording_Frame(const Recording_Frame& from);
  Recording_Frame(Recording_Frame&& from) noexcept
    : Recording_Frame() {
    *this = ::std::move(from);
  }

  inline Recording_Frame& operator=(const Recording_Frame& from) {
    CopyFrom(from);
    return *this;
  }
  inline Recording_Frame& operator=(Recording_Frame&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Recording_Frame& default_instance() {
    return *internal_default_instance();
  }
  static inline const Recording_Frame* internal_default_instance() {
    return reinterpret_cast<const Recording_Frame*>(
               &_Recording_Frame_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Recording_Frame& a, Recording_Frame& b) {
    a.Swap(&b);
  }
  inline void Swap(Recording_Frame* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Recording_Frame* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Recording_Frame* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Recording_Frame>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Recording_Frame& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Recording_Frame& from) {
    Recording_Frame::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Recording_Frame* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "demo.Recording.Frame";
  }
  protected:
  explicit Recording_Frame(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Recording_Frame_Node3D Node3D;

  // accessors -------------------------------------------------------

  enum : int {
    kNodesFieldNumber = 2,
    kTimeFieldNumber = 1,
  };
  // repeated .demo.Recording.Frame.Node3D nodes = 2;
  int nodes_size() const;
  private:
  int _internal_nodes_size() const;
  public:
  void clear_nodes();
  ::demo::Recording_Frame_Node3D* mutable_nodes(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::demo::Recording_Frame_Node3D >*
      mutable_nodes();
  private:
  const ::demo::Recording_Frame_Node3D& _internal_nodes(int index) const;
  ::demo::Recording_Frame_Node3D* _internal_add_nodes();
  public:
  const ::demo::Recording_Frame_Node3D& nodes(int index) const;
  ::demo::Recording_Frame_Node3D* add_nodes();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::demo::Recording_Frame_Node3D >&
      nodes() const;

  // float time = 1;
  void clear_time();
  float time() const;
  void set_time(float value);
  private:
  float _internal_time() const;
  void _internal_set_time(float value);
  public:

  // @@protoc_insertion_point(class_scope:demo.Recording.Frame)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::demo::Recording_Frame_Node3D > nodes_;
    float time_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_main_2eproto;
};
// -------------------------------------------------------------------

class Recording final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:demo.Recording) */ {
 public:
  inline Recording() : Recording(nullptr) {}
  ~Recording() override;
  explicit PROTOBUF_CONSTEXPR Recording(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Recording(const Recording& from);
  Recording(Recording&& from) noexcept
    : Recording() {
    *this = ::std::move(from);
  }

  inline Recording& operator=(const Recording& from) {
    CopyFrom(from);
    return *this;
  }
  inline Recording& operator=(Recording&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Recording& default_instance() {
    return *internal_default_instance();
  }
  static inline const Recording* internal_default_instance() {
    return reinterpret_cast<const Recording*>(
               &_Recording_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Recording& a, Recording& b) {
    a.Swap(&b);
  }
  inline void Swap(Recording* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Recording* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Recording* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Recording>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Recording& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Recording& from) {
    Recording::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Recording* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "demo.Recording";
  }
  protected:
  explicit Recording(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Recording_Frame Frame;

  // accessors -------------------------------------------------------

  enum : int {
    kFramesFieldNumber = 1,
  };
  // repeated .demo.Recording.Frame frames = 1;
  int frames_size() const;
  private:
  int _internal_frames_size() const;
  public:
  void clear_frames();
  ::demo::Recording_Frame* mutable_frames(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::demo::Recording_Frame >*
      mutable_frames();
  private:
  const ::demo::Recording_Frame& _internal_frames(int index) const;
  ::demo::Recording_Frame* _internal_add_frames();
  public:
  const ::demo::Recording_Frame& frames(int index) const;
  ::demo::Recording_Frame* add_frames();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::demo::Recording_Frame >&
      frames() const;

  // @@protoc_insertion_point(class_scope:demo.Recording)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::demo::Recording_Frame > frames_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_main_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Recording_Frame_Node3D

// string path = 11;
inline void Recording_Frame_Node3D::clear_path() {
  _impl_.path_.ClearToEmpty();
}
inline const std::string& Recording_Frame_Node3D::path() const {
  // @@protoc_insertion_point(field_get:demo.Recording.Frame.Node3D.path)
  return _internal_path();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Recording_Frame_Node3D::set_path(ArgT0&& arg0, ArgT... args) {
 
 _impl_.path_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:demo.Recording.Frame.Node3D.path)
}
inline std::string* Recording_Frame_Node3D::mutable_path() {
  std::string* _s = _internal_mutable_path();
  // @@protoc_insertion_point(field_mutable:demo.Recording.Frame.Node3D.path)
  return _s;
}
inline const std::string& Recording_Frame_Node3D::_internal_path() const {
  return _impl_.path_.Get();
}
inline void Recording_Frame_Node3D::_internal_set_path(const std::string& value) {
  
  _impl_.path_.Set(value, GetArenaForAllocation());
}
inline std::string* Recording_Frame_Node3D::_internal_mutable_path() {
  
  return _impl_.path_.Mutable(GetArenaForAllocation());
}
inline std::string* Recording_Frame_Node3D::release_path() {
  // @@protoc_insertion_point(field_release:demo.Recording.Frame.Node3D.path)
  return _impl_.path_.Release();
}
inline void Recording_Frame_Node3D::set_allocated_path(std::string* path) {
  if (path != nullptr) {
    
  } else {
    
  }
  _impl_.path_.SetAllocated(path, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.path_.IsDefault()) {
    _impl_.path_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:demo.Recording.Frame.Node3D.path)
}

// float x = 1;
inline void Recording_Frame_Node3D::clear_x() {
  _impl_.x_ = 0;
}
inline float Recording_Frame_Node3D::_internal_x() const {
  return _impl_.x_;
}
inline float Recording_Frame_Node3D::x() const {
  // @@protoc_insertion_point(field_get:demo.Recording.Frame.Node3D.x)
  return _internal_x();
}
inline void Recording_Frame_Node3D::_internal_set_x(float value) {
  
  _impl_.x_ = value;
}
inline void Recording_Frame_Node3D::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:demo.Recording.Frame.Node3D.x)
}

// float y = 2;
inline void Recording_Frame_Node3D::clear_y() {
  _impl_.y_ = 0;
}
inline float Recording_Frame_Node3D::_internal_y() const {
  return _impl_.y_;
}
inline float Recording_Frame_Node3D::y() const {
  // @@protoc_insertion_point(field_get:demo.Recording.Frame.Node3D.y)
  return _internal_y();
}
inline void Recording_Frame_Node3D::_internal_set_y(float value) {
  
  _impl_.y_ = value;
}
inline void Recording_Frame_Node3D::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:demo.Recording.Frame.Node3D.y)
}

// float z = 3;
inline void Recording_Frame_Node3D::clear_z() {
  _impl_.z_ = 0;
}
inline float Recording_Frame_Node3D::_internal_z() const {
  return _impl_.z_;
}
inline float Recording_Frame_Node3D::z() const {
  // @@protoc_insertion_point(field_get:demo.Recording.Frame.Node3D.z)
  return _internal_z();
}
inline void Recording_Frame_Node3D::_internal_set_z(float value) {
  
  _impl_.z_ = value;
}
inline void Recording_Frame_Node3D::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:demo.Recording.Frame.Node3D.z)
}

// float rx = 4;
inline void Recording_Frame_Node3D::clear_rx() {
  _impl_.rx_ = 0;
}
inline float Recording_Frame_Node3D::_internal_rx() const {
  return _impl_.rx_;
}
inline float Recording_Frame_Node3D::rx() const {
  // @@protoc_insertion_point(field_get:demo.Recording.Frame.Node3D.rx)
  return _internal_rx();
}
inline void Recording_Frame_Node3D::_internal_set_rx(float value) {
  
  _impl_.rx_ = value;
}
inline void Recording_Frame_Node3D::set_rx(float value) {
  _internal_set_rx(value);
  // @@protoc_insertion_point(field_set:demo.Recording.Frame.Node3D.rx)
}

// float ry = 5;
inline void Recording_Frame_Node3D::clear_ry() {
  _impl_.ry_ = 0;
}
inline float Recording_Frame_Node3D::_internal_ry() const {
  return _impl_.ry_;
}
inline float Recording_Frame_Node3D::ry() const {
  // @@protoc_insertion_point(field_get:demo.Recording.Frame.Node3D.ry)
  return _internal_ry();
}
inline void Recording_Frame_Node3D::_internal_set_ry(float value) {
  
  _impl_.ry_ = value;
}
inline void Recording_Frame_Node3D::set_ry(float value) {
  _internal_set_ry(value);
  // @@protoc_insertion_point(field_set:demo.Recording.Frame.Node3D.ry)
}

// float rz = 6;
inline void Recording_Frame_Node3D::clear_rz() {
  _impl_.rz_ = 0;
}
inline float Recording_Frame_Node3D::_internal_rz() const {
  return _impl_.rz_;
}
inline float Recording_Frame_Node3D::rz() const {
  // @@protoc_insertion_point(field_get:demo.Recording.Frame.Node3D.rz)
  return _internal_rz();
}
inline void Recording_Frame_Node3D::_internal_set_rz(float value) {
  
  _impl_.rz_ = value;
}
inline void Recording_Frame_Node3D::set_rz(float value) {
  _internal_set_rz(value);
  // @@protoc_insertion_point(field_set:demo.Recording.Frame.Node3D.rz)
}

// float sx = 7;
inline void Recording_Frame_Node3D::clear_sx() {
  _impl_.sx_ = 0;
}
inline float Recording_Frame_Node3D::_internal_sx() const {
  return _impl_.sx_;
}
inline float Recording_Frame_Node3D::sx() const {
  // @@protoc_insertion_point(field_get:demo.Recording.Frame.Node3D.sx)
  return _internal_sx();
}
inline void Recording_Frame_Node3D::_internal_set_sx(float value) {
  
  _impl_.sx_ = value;
}
inline void Recording_Frame_Node3D::set_sx(float value) {
  _internal_set_sx(value);
  // @@protoc_insertion_point(field_set:demo.Recording.Frame.Node3D.sx)
}

// float sy = 8;
inline void Recording_Frame_Node3D::clear_sy() {
  _impl_.sy_ = 0;
}
inline float Recording_Frame_Node3D::_internal_sy() const {
  return _impl_.sy_;
}
inline float Recording_Frame_Node3D::sy() const {
  // @@protoc_insertion_point(field_get:demo.Recording.Frame.Node3D.sy)
  return _internal_sy();
}
inline void Recording_Frame_Node3D::_internal_set_sy(float value) {
  
  _impl_.sy_ = value;
}
inline void Recording_Frame_Node3D::set_sy(float value) {
  _internal_set_sy(value);
  // @@protoc_insertion_point(field_set:demo.Recording.Frame.Node3D.sy)
}

// float sz = 9;
inline void Recording_Frame_Node3D::clear_sz() {
  _impl_.sz_ = 0;
}
inline float Recording_Frame_Node3D::_internal_sz() const {
  return _impl_.sz_;
}
inline float Recording_Frame_Node3D::sz() const {
  // @@protoc_insertion_point(field_get:demo.Recording.Frame.Node3D.sz)
  return _internal_sz();
}
inline void Recording_Frame_Node3D::_internal_set_sz(float value) {
  
  _impl_.sz_ = value;
}
inline void Recording_Frame_Node3D::set_sz(float value) {
  _internal_set_sz(value);
  // @@protoc_insertion_point(field_set:demo.Recording.Frame.Node3D.sz)
}

// bool visible = 10;
inline void Recording_Frame_Node3D::clear_visible() {
  _impl_.visible_ = false;
}
inline bool Recording_Frame_Node3D::_internal_visible() const {
  return _impl_.visible_;
}
inline bool Recording_Frame_Node3D::visible() const {
  // @@protoc_insertion_point(field_get:demo.Recording.Frame.Node3D.visible)
  return _internal_visible();
}
inline void Recording_Frame_Node3D::_internal_set_visible(bool value) {
  
  _impl_.visible_ = value;
}
inline void Recording_Frame_Node3D::set_visible(bool value) {
  _internal_set_visible(value);
  // @@protoc_insertion_point(field_set:demo.Recording.Frame.Node3D.visible)
}

// -------------------------------------------------------------------

// Recording_Frame

// float time = 1;
inline void Recording_Frame::clear_time() {
  _impl_.time_ = 0;
}
inline float Recording_Frame::_internal_time() const {
  return _impl_.time_;
}
inline float Recording_Frame::time() const {
  // @@protoc_insertion_point(field_get:demo.Recording.Frame.time)
  return _internal_time();
}
inline void Recording_Frame::_internal_set_time(float value) {
  
  _impl_.time_ = value;
}
inline void Recording_Frame::set_time(float value) {
  _internal_set_time(value);
  // @@protoc_insertion_point(field_set:demo.Recording.Frame.time)
}

// repeated .demo.Recording.Frame.Node3D nodes = 2;
inline int Recording_Frame::_internal_nodes_size() const {
  return _impl_.nodes_.size();
}
inline int Recording_Frame::nodes_size() const {
  return _internal_nodes_size();
}
inline void Recording_Frame::clear_nodes() {
  _impl_.nodes_.Clear();
}
inline ::demo::Recording_Frame_Node3D* Recording_Frame::mutable_nodes(int index) {
  // @@protoc_insertion_point(field_mutable:demo.Recording.Frame.nodes)
  return _impl_.nodes_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::demo::Recording_Frame_Node3D >*
Recording_Frame::mutable_nodes() {
  // @@protoc_insertion_point(field_mutable_list:demo.Recording.Frame.nodes)
  return &_impl_.nodes_;
}
inline const ::demo::Recording_Frame_Node3D& Recording_Frame::_internal_nodes(int index) const {
  return _impl_.nodes_.Get(index);
}
inline const ::demo::Recording_Frame_Node3D& Recording_Frame::nodes(int index) const {
  // @@protoc_insertion_point(field_get:demo.Recording.Frame.nodes)
  return _internal_nodes(index);
}
inline ::demo::Recording_Frame_Node3D* Recording_Frame::_internal_add_nodes() {
  return _impl_.nodes_.Add();
}
inline ::demo::Recording_Frame_Node3D* Recording_Frame::add_nodes() {
  ::demo::Recording_Frame_Node3D* _add = _internal_add_nodes();
  // @@protoc_insertion_point(field_add:demo.Recording.Frame.nodes)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::demo::Recording_Frame_Node3D >&
Recording_Frame::nodes() const {
  // @@protoc_insertion_point(field_list:demo.Recording.Frame.nodes)
  return _impl_.nodes_;
}

// -------------------------------------------------------------------

// Recording

// repeated .demo.Recording.Frame frames = 1;
inline int Recording::_internal_frames_size() const {
  return _impl_.frames_.size();
}
inline int Recording::frames_size() const {
  return _internal_frames_size();
}
inline void Recording::clear_frames() {
  _impl_.frames_.Clear();
}
inline ::demo::Recording_Frame* Recording::mutable_frames(int index) {
  // @@protoc_insertion_point(field_mutable:demo.Recording.frames)
  return _impl_.frames_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::demo::Recording_Frame >*
Recording::mutable_frames() {
  // @@protoc_insertion_point(field_mutable_list:demo.Recording.frames)
  return &_impl_.frames_;
}
inline const ::demo::Recording_Frame& Recording::_internal_frames(int index) const {
  return _impl_.frames_.Get(index);
}
inline const ::demo::Recording_Frame& Recording::frames(int index) const {
  // @@protoc_insertion_point(field_get:demo.Recording.frames)
  return _internal_frames(index);
}
inline ::demo::Recording_Frame* Recording::_internal_add_frames() {
  return _impl_.frames_.Add();
}
inline ::demo::Recording_Frame* Recording::add_frames() {
  ::demo::Recording_Frame* _add = _internal_add_frames();
  // @@protoc_insertion_point(field_add:demo.Recording.frames)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::demo::Recording_Frame >&
Recording::frames() const {
  // @@protoc_insertion_point(field_list:demo.Recording.frames)
  return _impl_.frames_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace demo

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_main_2eproto
